<section class="has-actions style-default-bright">
    <!-- BEGIN INBOX -->
    <div class="section-body">
        <div class="row">
               <!-- BEGIN MAIL COMPOSE -->
            <div class="col-xs-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2 col-xs-offset-0">
                <h3>#compose#</h3>
                #open-form#


                    <div class="col-xs-12 col-sm-6 col-md-8">
                        <fieldset>
                            <legend>GERAL</legend>
                            #geral#
                            <div class="clearfix"></div>
                        </fieldset>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <fieldset>
                            <legend>FORMULARIO DE ADICIONAL</legend>
                            <div class="row">
                                <div class="col-md-12">
                                    #controller#
                                    <div class="clearfix"></div>
                                </div>
                                <div class="col-md-12">
                                    #datas#
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </fieldset>
                    </div>


                    <div class="clearfix"></div>

                    <!-- BEGIN SECTION ACTION -->
                    <div class="section-action style-primary">
                        <div class="section-action-row">

                        </div>
                        <div class="section-floating-action-row">
                            #btn-voltar#
                              #comando#

                        </div>
                    </div>
                    #close-form#
            </div>
        </div>
                <!-- END INBOX -->
                <!-- END SECTION ACTION -->
</section>