<div class="col-md-12">
    <div class="img-add images">%s #imagePriview# </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">SELECIONE</span>
            <div class="input-group-content">
                %s
            </div>
													<span class="input-group-addon">
													<i class="fa  fa-picture-o"></i>
													</span>
        </div>
    </div>
    <input type="file" class="atachament" id="atachament" name="atachament">
</div><!--end .form-group -->