<li class="tile">
    <a class="tile-content ink-reaction">
        <div class="tile-icon">
            #images#
        </div>
        <div class="tile-text">
            #title#
            <small>
                #description#
            </small>
        </div>
    </a>
    <a href="#rota-editar#" class="btn btn-flat ink-reaction btn-default" role="button"><i class="fa fa-edit"></i> </a>
    <a href="#rota-excluir#" class="btn btn-flat ink-reaction btn-danger excluir" role="button"><i class="fa fa-trash-o"></i> </a>
    <a href="#rota-search#" class="btn btn-flat ink-reaction btn-default search-item hidden-xs" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Loading..." role="button"><i class="fa fa-search"></i> </a>
  </li>
<li class="divider-inset"></li>